### ISSUE TITLE
how to mount the nginx/php log and the MySQL database

### ISSUE THREAD

**Issue by xu4wang** [fbraz3/lemp-docker#5]
I create a docker compose file

```
version: '3.8'  
services:
  web:
    image: fbraz3/lnmp
    volumes:
      - ./:/app/public/
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:3306:3306"
```

Shall I put something under volumes to check the logs and save the database in the host?

BR,Austin

**Comment by xu4wang** [comment]
Tried below, seems the nginx log and database files are created. However, after the configuration change, the mysql db is no longer accessible by my app and pma.

```
version: '3.8'  
services:
  web:
    image: fbraz3/lnmp
    volumes:
      - ./app:/app/public/
      - ./nginx_logs:/var/log/nginx  
      - ./mariadb_data:/var/lib/mysql  
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:3306:3306"
```

**Comment by xu4wang** [comment]
Finnally, this one works. A named volume managed by docker should be used in Mac.

```
version: '3.8'
services:
  wp:
    image: fbraz3/lnmp
    volumes:
      - ./app:/app/public/
      - ./nginx_logs:/var/log/nginx 
      - my-datavolume:/var/lib/mysql  
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:3306:3306"
volumes:
  my-datavolume:
```
