### ISSUE TITLE
Unable to connect to MySQL database.

### ISSUE THREAD

**Issue by n08i40k** [fbraz3/lemp-docker#6]
docker-compose.yml
```
services:
  web:
    image: fbraz3/lnmp:latest
    volumes:
      - ./:/app/public
    ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:3306:3306"
```

Connection configuration in DBeaver CE
![image](https://github.com/user-attachments/assets/70c8e3d1-cbed-4380-b616-0b4bcc29e8ec)

Error displayed when connecting to the database
![image](https://github.com/user-attachments/assets/8664ace1-33ed-482a-994e-2b3d62c75b4f)
